//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoControl.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageError() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PontoControl.Exceptions.ResourceMessageError", typeof(ResourceMessageError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha atual não é válida..
        /// </summary>
        public static string current_password_invalid {
            get {
                return ResourceManager.GetString("current_password_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cpf é inválido..
        /// </summary>
        public static string document_invalid {
            get {
                return ResourceManager.GetString("document_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As marcações devem se limitar a quatro por dia..
        /// </summary>
        public static string exceeded_markings {
            get {
                return ResourceManager.GetString("exceeded_markings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token expirado. Faça login novamente..
        /// </summary>
        public static string expired_token {
            get {
                return ResourceManager.GetString("expired_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email ou Senha inválidos..
        /// </summary>
        public static string invalid_login {
            get {
                return ResourceManager.GetString("invalid_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço não pode ser vazio..
        /// </summary>
        public static string marking_address_empty {
            get {
                return ResourceManager.GetString("marking_address_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hora não pode ser vazio..
        /// </summary>
        public static string marking_hour_empty {
            get {
                return ResourceManager.GetString("marking_hour_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem permissão para essa requisição..
        /// </summary>
        public static string unauthorized_token {
            get {
                return ResourceManager.GetString("unauthorized_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido..
        /// </summary>
        public static string unknow_error {
            get {
                return ResourceManager.GetString("unknow_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email não pode ser nulo..
        /// </summary>
        public static string user_email_empty {
            get {
                return ResourceManager.GetString("user_email_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email ou senhas não são válidos..
        /// </summary>
        public static string user_email_repeated {
            get {
                return ResourceManager.GetString("user_email_repeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do usuário não pode ser nulo..
        /// </summary>
        public static string user_firstname_empty {
            get {
                return ResourceManager.GetString("user_firstname_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobrenome do usuário não pode ser nulo..
        /// </summary>
        public static string user_lastname_empty {
            get {
                return ResourceManager.GetString("user_lastname_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo senha não pode ser nulo..
        /// </summary>
        public static string user_password_empty {
            get {
                return ResourceManager.GetString("user_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha deve ter pelo menos 6 caracteres..
        /// </summary>
        public static string user_password_minlength {
            get {
                return ResourceManager.GetString("user_password_minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo não pode ser nulo..
        /// </summary>
        public static string user_position_empty {
            get {
                return ResourceManager.GetString("user_position_empty", resourceCulture);
            }
        }
    }
}
